export const REGISTRATION_WINDOW_MS = 24 * 60 * 60 * 1000
export const REGISTRATION_MAX_ATTEMPTS = 5

export const LOGIN_WINDOW_MS = 15 * 60 * 1000
export const LOGIN_MAX_ATTEMPTS = 5

export const VERIFICATION_WINDOW_MS = 15 * 60 * 1000
export const VERIFICATION_MAX_ATTEMPTS = 10

export const PASSWORD_RESET_REQUEST_WINDOW_MS = 15 * 60 * 1000
export const PASSWORD_RESET_REQUEST_MAX_ATTEMPTS = 5

export const PASSWORD_RESET_WINDOW_MS = 15 * 60 * 1000
export const PASSWORD_RESET_MAX_ATTEMPTS = 10

export const FILE_UPLOAD_WINDOW_MS = 60 * 60 * 1000
export const FILE_UPLOAD_MAX_ATTEMPTS = 30
