name: CD

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_KEY_PASSPHRASE }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/eanathos/antIdTraining
            git pull --rebase origin master
            npm run docker:up
